version: '3.9'

services:

  mongo:
    image: mongo:4.4
    restart: always
    container_name: BeGo-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: 'mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/'

volumes:
  data: